/**:
  ros__parameters:
    # 2. Playing Environment
    field:
      length: 12.0
      width: 9.0
      goal_width: 1.8

    # 3. Robots
    robots:
      max_num_in_field: 11
      num_of_ids: 16
      