/**:
  ros__parameters:
    div_a_field:  # division_aのフィールドルールを基準に、座標を正規化する
      length: 12.0
      width: 9.0
      robot_diameter: 0.18
      ball_diameter: 0.043
      
    physics:
      gravity: 9.81  # 重力加速度
      ball_friction_coeff: 0.03  # ボールの摩擦係数
