/**:
  ros__parameters:
    div_a_field:  # division_aのフィールドルールを基準に、座標を正規化する
      length: 12.0
      width: 9.0
      robot_diameter: 0.18
      ball_diameter: 0.043
      
    physics:
      gravity: 9.81  # 重力加速度
      ball_friction_coeff: 0.03  # ボールの摩擦係数
      
    kick_power:
      max_kick_power: 6.0  # 最大キック力 [m/s] (6.5 m/sを越えてはいけない)
      max_shoot_speed: 5.5  # シュート時の最大速度 [m/s]
      max_pass_speed: 4.0  # パス時の最大速度 [m/s] 
      min_pass_speed: 2.0  # パス時の最小速度 [m/s]
      tapping_kick_power: 2.0  # タップキック用のパワー [m/s] (ドリブル用)
