version: "3"
services:
  consai:
    image: ghcr.io/ssl-roots/consai_ros2:devcontainer
    command:
      [
        "bash",
        "-c",
        "cd ~/ros2_ws/src/consai_ros2/consai_web_ui/consai_web_ui && npm install && npm run dev"
      ]
    volumes:
      - ../:/home/vscode/ros2_ws/src/consai_ros2
    ports:
      - "3000:3000"

  rosbridge_server:
    image: ghcr.io/ssl-roots/consai_ros2:devcontainer
    command:
      [
        "sh",
        "-c",
        ". /opt/ros/humble/setup.sh && . ~/ros2_ws/install/setup.sh && ros2 launch rosbridge_server rosbridge_websocket_launch.xml",
      ]
    ports:
      - "9090:9090"

  grsim:
    image: robocupssl/grsim

  ssl-game-controller:
    image: robocupssl/ssl-game-controller
    command: ["-address", ":8081"]
    ports:
      - "8081:8081"
