version: '3.8'
services:
  grsim:
    image: ghcr.io/ssl-roots/docker_images/grsim:main
    container_name: grsim
    network_mode: host
    command: |
      ./grSim --headless -platform offscreen
    tty: true
    stdin_open: true
    restart: "no"

  consai_ros2:
    image: ghcr.io/ssl-roots/consai_ros2:humble
    container_name: consai
    network_mode: host
    volumes:
      - "../:/root/ros2_ws/src/consai_ros2"  # Mount the repository to the container
    command: |
      bash -c "
      colcon build --symlink-install &&
      source install/setup.bash &&
      ros2 launch consai_examples start.launch.py game:=true invert:=false vision_port:=10020 gui:=false
      "
    tty: true
    stdin_open: true
    restart: "no"