# This msg file is a copy of 'messages_robocup_ssl_detection_tracked.proto'
# https://github.com/RoboCup-SSL/ssl-vision/blob/master/src/shared/proto/messages_robocup_ssl_detection_tracked.proto

# A unique robot id with team information

# The team color of the robot
# team not set
uint32 TEAM_COLOR_UNKNOWN = 0
# yellow team
uint32 TEAM_COLOR_YELLOW = 1
# blue team
uint32 TEAM_COLOR_BLUE = 2

# The robot number
uint32 id
# The team color
uint32 team_color