controller:
  ros__parameters:
    vx_p: 2.0
    vx_i: 0.0
    vx_d: 0.1
    vx_i_max: 0.0
    vx_i_min: 0.0
    vx_antiwindup: false

    vy_p: 2.0
    vy_i: 0.0
    vy_d: 0.1
    vy_i_max: 0.0
    vy_i_min: 0.0
    vy_antiwindup: false

    vtheta_p: 1.5
    vtheta_i: 0.0
    vtheta_d: 0.1
    vtheta_i_max: 0.0
    vtheta_i_min: 0.0
    vtheta_antiwindup: false
