vx_p: 3.0
vx_i: 0.0
vx_d: 0.7
vx_i_max: 0.0
vx_i_min: 0.0
vx_antiwindup: false

vy_p: 3.0
vy_i: 0.0
vy_d: 0.7
vy_i_max: 0.0
vy_i_min: 0.0
vy_antiwindup: false

vtheta_p: 2.0
vtheta_i: 0.0
vtheta_d: 0.0
vtheta_i_max: 0.0
vtheta_i_min: 0.0
vtheta_antiwindup: false

max_acceleration_xy: 2.0  # m/s^2
max_acceleration_theta: 5.0  # rad/s^2

max_velocity_xy: 2.0  # m/s^2
max_velocity_theta: 5.0  # rad/s^2
