name: build_and_lint

on:
  push:
    branches:
      - main
      - '**-devel'
    paths-ignore:
      - '**.md'
      - '.docker/**'
      - '.github/workflows/build_docker_image.yaml'
      - '.github/workflows/build_docker_image_for_ci.yaml'
      - '.github/workflows/scenario_test.yaml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.docker/**'
      - '.github/workflows/build_docker_image.yaml'
      - '.github/workflows/build_docker_image_for_ci.yaml'
      - '.github/workflows/scenario_test.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_lint:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ssl-roots/consai_ros2:humble

    steps:
      - uses: actions/checkout@v4

      - name: Setup colcon workspace
        run: |
          mkdir -p ~/ros2_ws/src
          cp -r . ~/ros2_ws/src/
          cd ~/ros2_ws
          source /opt/ros/humble/setup.bash
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build with colcon
        run: |
          cd ~/ros2_ws
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_direct+

      - name: Lint (ament_lint)
        run: |
          cd ~/ros2_ws
          source install/setup.bash
          colcon test --packages-select <lint対象パッケージ名>
          colcon test-result --verbose
