name: build_and_lint

on:
  push:
    branches:
      - main
      - '**-devel'
    paths-ignore:
      - '**.md'
      - '.docker/**'
      - '.github/workflows/build_docker_image.yaml'
      - '.github/workflows/build_docker_image_for_ci.yaml'
      - '.github/workflows/scenario_test.yaml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.docker/**'
      - '.github/workflows/build_docker_image.yaml'
      - '.github/workflows/build_docker_image_for_ci.yaml'
      - '.github/workflows/scenario_test.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_lint:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ssl-roots/consai_ros2:humble-light

    steps:
      - uses: actions/checkout@v4

      - name: Copy consai_ros2 to workspace
        run: |
          cp -r . /root/ros2_ws/src/consai_ros2
        shell: bash

      - name: Build with colcon
        run: |
          cd /root/ros2_ws
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install
        shell: bash

      - name: Lint (ament_lint)
        run: |
          cd /root/ros2_ws
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          colcon test --event-handlers console_direct+ --ctest-args -V
          colcon test-result --verbose
        shell: bash
