name: Create and publish a Docker image for CI

on:
  workflow_call:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: humble}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long,prefix=${{ matrix.env.ROS_DISTRO }}-light-sha-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: .docker/ci/Dockerfile
          build-args: ROS_DISTRO=${{ matrix.env.ROS_DISTRO }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # - name: Save SHA
      #   run: echo "${{ github.sha }}" > image_sha.txt

      # - name: Upload SHA as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: image_sha
      #     path: image_sha.txt
